"""structure canonique

Revision ID: 44a7016dcb59
Revises: 740a30fefef4
Create Date: 2026-07-11 11:35:24.378154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44a7016dcb59'
down_revision: Union[str, None] = '740a30fefef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structure', sa.Column('canonique_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_structure_canonique_id'), 'structure', ['canonique_id'], unique=False)
    op.create_foreign_key(None, 'structure', 'structure', ['canonique_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'structure', type_='foreignkey')
    op.drop_index(op.f('ix_structure_canonique_id'), table_name='structure')
    op.drop_column('structure', 'canonique_id')
    # ### end Alembic commands ###
