"""membres du gouvernement

Revision ID: 47cbc2891edc
Revises: 44a7016dcb59
Create Date: 2026-07-11 12:36:52.154927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47cbc2891edc'
down_revision: Union[str, None] = '44a7016dcb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membre_gouvernement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('civilite', sa.String(length=100), nullable=True),
    sa.Column('nom_complet', sa.String(length=300), nullable=False),
    sa.Column('poste', sa.String(length=500), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membre_gouvernement_statut_validation'), 'membre_gouvernement', ['statut_validation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membre_gouvernement_statut_validation'), table_name='membre_gouvernement')
    op.drop_table('membre_gouvernement')
    # ### end Alembic commands ###
