"""photo_url membre_gouvernement

Revision ID: 48200271c853
Revises: 6c023fffaa3e
Create Date: 2026-07-11 17:44:29.607646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48200271c853'
down_revision: Union[str, None] = '6c023fffaa3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membre_gouvernement', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membre_gouvernement', 'photo_url')
    # ### end Alembic commands ###
