"""schema initial

Revision ID: 5edc2dbc742d
Revises: 
Create Date: 2026-07-10 18:11:05.828951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5edc2dbc742d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_complet', sa.String(length=300), nullable=False),
    sa.Column('nom_normalise', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personne_nom_normalise'), 'personne', ['nom_normalise'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('url_base', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('cadence', sa.String(length=50), nullable=False),
    sa.Column('licence', sa.String(length=200), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=500), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_sigle'), 'structure', ['sigle'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('titre', sa.String(length=1000), nullable=True),
    sa.Column('type_doc', sa.String(length=50), nullable=False),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_collecte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_contenu', sa.String(length=64), nullable=True),
    sa.Column('fichier', sa.String(length=500), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('texte_extrait', sa.Text(), nullable=True),
    sa.Column('statut_extraction', sa.String(length=20), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'url', 'hash_contenu', name='uq_document_source_url_hash')
    )
    op.create_index(op.f('ix_document_date_publication'), 'document', ['date_publication'], unique=False)
    op.create_index(op.f('ix_document_hash_contenu'), 'document', ['hash_contenu'], unique=False)
    op.create_index(op.f('ix_document_type_doc'), 'document', ['type_doc'], unique=False)
    op.create_index(op.f('ix_document_url'), 'document', ['url'], unique=False)
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('nb_nouveaux', sa.Integer(), nullable=False),
    sa.Column('nb_vus', sa.Integer(), nullable=False),
    sa.Column('erreurs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('poste', sa.String(length=500), nullable=False),
    sa.Column('date_effet', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personne.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomination_statut_validation'), 'nomination', ['statut_validation'], unique=False)
    op.create_table('mandat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('poste', sa.String(length=500), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('nomination_debut_id', sa.Integer(), nullable=True),
    sa.Column('nomination_fin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nomination_debut_id'], ['nomination.id'], ),
    sa.ForeignKeyConstraint(['nomination_fin_id'], ['nomination.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personne.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Recherche plein texte : colonne générée + index GIN (non mappée dans l'ORM)
    op.execute(
        """
        ALTER TABLE document ADD COLUMN tsv tsvector
        GENERATED ALWAYS AS (
            to_tsvector('french', coalesce(titre, '') || ' ' || coalesce(texte_extrait, ''))
        ) STORED
        """
    )
    op.create_index("ix_document_tsv", "document", ["tsv"], postgresql_using="gin")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandat')
    op.drop_index(op.f('ix_nomination_statut_validation'), table_name='nomination')
    op.drop_table('nomination')
    op.drop_table('run')
    op.drop_index(op.f('ix_document_url'), table_name='document')
    op.drop_index(op.f('ix_document_type_doc'), table_name='document')
    op.drop_index(op.f('ix_document_hash_contenu'), table_name='document')
    op.drop_index(op.f('ix_document_date_publication'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_structure_sigle'), table_name='structure')
    op.drop_table('structure')
    op.drop_table('source')
    op.drop_index(op.f('ix_personne_nom_normalise'), table_name='personne')
    op.drop_table('personne')
    # ### end Alembic commands ###
