"""marche autorite nullable

Revision ID: 5fdbd4d6d5a6
Revises: aa89435d2dd0
Create Date: 2026-07-14 01:10:31.208407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fdbd4d6d5a6'
down_revision: Union[str, None] = 'aa89435d2dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marche', 'autorite',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marche', 'autorite',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###
