"""deputes

Revision ID: 6a4580e4b593
Revises: 47cbc2891edc
Create Date: 2026-07-11 13:11:17.116957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a4580e4b593'
down_revision: Union[str, None] = '47cbc2891edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_complet', sa.String(length=300), nullable=False),
    sa.Column('legislature', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_complet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depute')
    # ### end Alembic commands ###
