"""dotation_budgetaire

Revision ID: 6c023fffaa3e
Revises: 6a4580e4b593
Create Date: 2026-07-11 17:20:20.677042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c023fffaa3e'
down_revision: Union[str, None] = '6a4580e4b593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dotation_budgetaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('ministere', sa.String(length=300), nullable=False),
    sa.Column('montant_fcfa', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_libre', sa.String(length=500), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dotation_budgetaire_exercice'), 'dotation_budgetaire', ['exercice'], unique=False)
    op.create_index(op.f('ix_dotation_budgetaire_statut_validation'), 'dotation_budgetaire', ['statut_validation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dotation_budgetaire_statut_validation'), table_name='dotation_budgetaire')
    op.drop_index(op.f('ix_dotation_budgetaire_exercice'), table_name='dotation_budgetaire')
    op.drop_table('dotation_budgetaire')
    # ### end Alembic commands ###
