"""matricules personne nomination

Revision ID: 957b8d6194cf
Revises: e19bc4da71a6
Create Date: 2026-07-11 22:09:52.136988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '957b8d6194cf'
down_revision: Union[str, None] = 'e19bc4da71a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomination', sa.Column('matricule', sa.String(length=30), nullable=True))
    op.add_column('personne', sa.Column('matricule', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_personne_matricule'), 'personne', ['matricule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personne_matricule'), table_name='personne')
    op.drop_column('personne', 'matricule')
    op.drop_column('nomination', 'matricule')
    # ### end Alembic commands ###
