"""repartition_budgetaire

Revision ID: 9b19367fcb72
Revises: c10176c3eb33
Create Date: 2026-07-11 19:27:28.391182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b19367fcb72'
down_revision: Union[str, None] = 'c10176c3eb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repartition_budgetaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('sens', sa.String(length=10), nullable=False),
    sa.Column('libelle', sa.String(length=300), nullable=False),
    sa.Column('montant_fcfa', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_libre', sa.String(length=500), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repartition_budgetaire_exercice'), 'repartition_budgetaire', ['exercice'], unique=False)
    op.create_index(op.f('ix_repartition_budgetaire_sens'), 'repartition_budgetaire', ['sens'], unique=False)
    op.create_index(op.f('ix_repartition_budgetaire_statut_validation'), 'repartition_budgetaire', ['statut_validation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repartition_budgetaire_statut_validation'), table_name='repartition_budgetaire')
    op.drop_index(op.f('ix_repartition_budgetaire_sens'), table_name='repartition_budgetaire')
    op.drop_index(op.f('ix_repartition_budgetaire_exercice'), table_name='repartition_budgetaire')
    op.drop_table('repartition_budgetaire')
    # ### end Alembic commands ###
