"""marche (attributions)

Revision ID: aa89435d2dd0
Revises: 957b8d6194cf
Create Date: 2026-07-14 00:01:28.831397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa89435d2dd0'
down_revision: Union[str, None] = '957b8d6194cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('autorite', sa.String(length=400), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=True),
    sa.Column('mode', sa.String(length=120), nullable=True),
    sa.Column('attributaire', sa.String(length=400), nullable=True),
    sa.Column('montant_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('date_attribution', sa.Date(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marche_statut_validation'), 'marche', ['statut_validation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marche_statut_validation'), table_name='marche')
    op.drop_table('marche')
    # ### end Alembic commands ###
