"""genre membre_gouvernement

Revision ID: c10176c3eb33
Revises: 48200271c853
Create Date: 2026-07-11 17:47:27.155437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c10176c3eb33'
down_revision: Union[str, None] = '48200271c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membre_gouvernement', sa.Column('genre', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membre_gouvernement', 'genre')
    # ### end Alembic commands ###
