"""role depute

Revision ID: e19bc4da71a6
Revises: 9b19367fcb72
Create Date: 2026-07-11 21:25:18.721687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e19bc4da71a6'
down_revision: Union[str, None] = '9b19367fcb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depute', sa.Column('role', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('depute', 'role')
    # ### end Alembic commands ###
